apiVersion: apps/v1
kind: Deployment
metadata:
    name: sa-2020-03-rs01
spec:
    replicas: 3
    selector:
       matchLabels:
           app: sa-2020-03-app
    template:
       metadata:
          labels:
             app: sa-2020-03-app
       spec:
          containers:
          - name: sa-2020-03-docker01
            image: andreyshitov/sa-2020-03-docker01:0.1
            ports:
              - containerPort: 8000
            livenessProbe:
              httpGet:
                port: 8000
                path: /health
              initialDelaySeconds: 10
              periodSeconds: 5
              timeoutSeconds: 4
            readinessProbe:
              httpGet:
                port: 8000
                path: /health
              initialDelaySeconds: 10
              periodSeconds: 5
